<?php

/**
 * This file is part of the PacketeryNette Framework (https://nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

declare(strict_types=1);

namespace PacketeryNette\DI\Config\Adapters;

use PacketeryNette;


/**
 * Reading and generating PHP files.
 */
final class PhpAdapter implements PacketeryNette\DI\Config\Adapter
{
	use PacketeryNette\SmartObject;

	/**
	 * Reads configuration from PHP file.
	 */
	public function load(string $file): array
	{
		return require $file;
	}


	/**
	 * Generates configuration in PHP format.
	 */
	public function dump(array $data): string
	{
		return "<?php // generated by PacketeryNette \nreturn " . PacketeryNette\PhpGenerator\Helpers::dump($data) . ';';
	}
}
