<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.5',
            'version' => '6.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '9d4290de1cfd701f38099ef7e183b64b4b7b0c5e',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => '8e7d04f1f6450fef59366c399cfad4b9383aa30d',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'dc960a912984efb74d0a90222870c72c87f10c91',
            'dev_requirement' => false,
        ),
        'latte/latte' => array(
            'pretty_version' => 'v2.10.3',
            'version' => '2.10.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../latte/latte',
            'aliases' => array(),
            'reference' => 'dd2c58863e830c22a2c6b85af63f37b829d255df',
            'dev_requirement' => false,
        ),
        'nette/bootstrap' => array(
            'pretty_version' => 'v3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/bootstrap',
            'aliases' => array(),
            'reference' => 'efe6c30fc009451f59fe56f3b309eb85c48b2baf',
            'dev_requirement' => false,
        ),
        'nette/component-model' => array(
            'pretty_version' => 'v3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/component-model',
            'aliases' => array(),
            'reference' => '66409cf5507c77edb46ffa88cf6a92ff58395601',
            'dev_requirement' => false,
        ),
        'nette/di' => array(
            'pretty_version' => 'v3.0.8',
            'version' => '3.0.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/di',
            'aliases' => array(),
            'reference' => '1a3210f0f1f971db8a6e970c716c1cebd28b7ab0',
            'dev_requirement' => false,
        ),
        'nette/finder' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/finder',
            'aliases' => array(),
            'reference' => '4ad2c298eb8c687dd0e74ae84206a4186eeaed50',
            'dev_requirement' => false,
        ),
        'nette/forms' => array(
            'pretty_version' => 'v3.1.3',
            'version' => '3.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/forms',
            'aliases' => array(),
            'reference' => 'bfbef39b1f07dc5cdfeb7dba4843ee086ca0c065',
            'dev_requirement' => false,
        ),
        'nette/http' => array(
            'pretty_version' => 'v3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/http',
            'aliases' => array(),
            'reference' => 'c903d0f0b793ed2045a442f338e756e1d3954c22',
            'dev_requirement' => false,
        ),
        'nette/neon' => array(
            'pretty_version' => 'v3.2.2',
            'version' => '3.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/neon',
            'aliases' => array(),
            'reference' => 'e4ca6f4669121ca6876b1d048c612480e39a28d5',
            'dev_requirement' => false,
        ),
        'nette/php-generator' => array(
            'pretty_version' => 'v3.5.4',
            'version' => '3.5.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/php-generator',
            'aliases' => array(),
            'reference' => '59bb35ed6e8da95854fbf7b7d47dce6156b42915',
            'dev_requirement' => false,
        ),
        'nette/robot-loader' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/robot-loader',
            'aliases' => array(),
            'reference' => '3973cf3970d1de7b30888fd10b92dac9e0c2fd82',
            'dev_requirement' => false,
        ),
        'nette/schema' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/schema',
            'aliases' => array(),
            'reference' => 'f5ed39fc96358f922cedfd1e516f0dadf5d2be0d',
            'dev_requirement' => false,
        ),
        'nette/utils' => array(
            'pretty_version' => 'v3.2.3',
            'version' => '3.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/utils',
            'aliases' => array(),
            'reference' => '5c36cc1ba9bb6abb8a9e425cf054e0c3fd5b9822',
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '65bd267525e82759e7d8c4e8ceea44f398838e65',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '9a142215a36a3888e30d0a9eeea9766764e96976',
            'dev_requirement' => false,
        ),
        'tracy/tracy' => array(
            'pretty_version' => 'v2.8.6',
            'version' => '2.8.6.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tracy/tracy',
            'aliases' => array(),
            'reference' => 'f3d2d6a1230a0a1a7b116c071ae4937e5e30101a',
            'dev_requirement' => true,
        ),
    ),
);
