<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PacketerySymfony\\Polyfill\\Php72\\' => array($vendorDir . '/symfony/polyfill-php72'),
    'PacketerySymfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'PacketerySymfony\\Polyfill\\Intl\\Idn\\' => array($vendorDir . '/symfony/polyfill-intl-idn'),
    'PacketeryPsr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'PacketeryGuzzleHttp\\PacketeryPsr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'PacketeryGuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'PacketeryGuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
);
