<?php

// platform_check.php @generated by PacketeryComposer

$issues = array();

if (!(PHP_VERSION_ID >= 70200)) {
    $issues[] = 'Your PacketeryComposer dependencies require a PHP version ">= 7.2.0". You are running ' . PHP_VERSION . '.';
}

if ($issues) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, 'PacketeryComposer detected issues in your platform:' . PHP_EOL.PHP_EOL . implode(PHP_EOL, $issues) . PHP_EOL.PHP_EOL);
        } elseif (!headers_sent()) {
            echo 'PacketeryComposer detected issues in your platform:' . PHP_EOL.PHP_EOL . str_replace('You are running '.PHP_VERSION.'.', '', implode(PHP_EOL, $issues)) . PHP_EOL.PHP_EOL;
        }
    }
    trigger_error(
        'PacketeryComposer detected issues in your platform: ' . implode(' ', $issues),
        E_USER_ERROR
    );
}
