name: Code checking by sniffer
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  sniff:
    name: Run sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Running sniffer
        shell: bash
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/run-sniffer.sh"
          
          # run script
          "${GITHUB_WORKSPACE}/.github/run-sniffer.sh"
